### ISSUE TITLE
uid xxxxx cannot explicitly add accounts of type: xxxxxx

### ISSUE THREAD

**Issue by Kazehiro** [GoIntegro/react-native-account-manager#10]
i'am using react native 0.61.5 and getting that error, even when i use package name for account name parameter

**Comment by buse974** [comment]
Hi, same problem. I corrected it by adding
`        <service android:name="com.gointegro.accountmanager.AuthenticatorService">
            <intent-filter>
                <action android:name="android.accounts.AccountAuthenticator" />
            </intent-filter>
            <meta-data android:name="android.accounts.AccountAuthenticator" android:resource="@xml/authenticator" />
        </service>`

In the section "application" in Android/app/src/main/AndroidManifest.xml.

And a file authenticator.xml in Android/app/src/main/res/xml/authenticator.xml
 with in 
`<?xml version="1.0" encoding="utf-8"?>
<account-authenticator
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:accountType="com.tagncar"
        android:icon="@mipmap/ic_launcher_round"
        android:smallIcon="@mipmap/ic_launcher_round"
        android:label="@string/app_name"/>`

here is the documentation for the options
https://developer.android.com/training/sync-adapters/creating-authenticator

I hope I've helped you.

**Comment by MarcoScabbiolo** [comment]
This means the account you're trying to read was written by an app with a different signature than the one trying to read. Learn more here: https://developer.android.com/reference/android/accounts/AccountManager
