### ISSUE TITLE
Getting an empty list?

### ISSUE THREAD

**Issue by Norfeldt** [GoIntegro/react-native-account-manager#4]
What could be the logical reason for getting an empty list returned when I now that the debugged device has an account associated with it?

**Comment by winadiw** [comment]
https://stackoverflow.com/questions/52457350/getaccountsbytypecom-google-fails-to-list-my-google-account-for-minsdkversio

Looks like this method no longer works on Android 8.0

**Comment by MarcoScabbiolo** [comment]
It does work as long as you're accessing account created from the same app, or from an app that shares an underlying signature with the one thats calling the method. Asking the user for permission to access another account is not supported.
