### ISSUE TITLE
Getting empty array

### ISSUE THREAD

**Issue by basanthalluri** [GoIntegro/react-native-account-manager#5]
Hi  I am getting an empty array when integrated this code:

`AccountManager.getAccountsByType('gmail').then((accounts) => {
     console.log('available accounts', accounts);
      let [firstAccount] = accounts;
    })`

What should be the account name should be given to get list of available gmail accounts in our android device.

**Comment by KSRajkumar45** [comment]
Hi basanthalluri,
 How to get accounts?. Now i got undefined while using AccountManager.getAccountsByType('com.google'). But i'm successfully installed and linked the package.
i'm using like this.
 componentDidMount = async () => {
    try {
      AccountManager.getAccountsByType('accountName').then((accounts) => {
        console.log('available accounts', accounts);
      })
    }
    catch (err) {
      console.log('Error', err);
    }
  }

**Comment by MarcoScabbiolo** [comment]
It is the expected behaviour, your app doesn't have access to Gmail's accounts
