### ISSUE TITLE
How to get entire data?

### ISSUE THREAD

**Issue by basanthalluri** [GoIntegro/react-native-account-manager#6]
Hi,

When I used getAccount('com.google') I got the accounts but when I used this:

`AccountManager.getUserData(firstAccount, 'storedKey').then((storedData) => {
    // console.log('stored data for storeKey', storedData);
})
`
It throwing an error like 
**java.lang.SecurityException: uid 10204 cannot get user data for accounts of type: com.google**

Can you tell me how to get the entire data of those accounts?

**Comment by MarcoScabbiolo** [comment]
You can only access accounts visible to your app. See https://developer.android.com/reference/android/accounts/AccountManager.html for more information.
