### ISSUE TITLE
'AccountManager' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by marcodafonseca** [GoIntegro/react-native-account-manager#9]
Hi

I have been following the examples provided, but VS Code is throwing the following error for me: "'AccountManager' only refers to a type, but is being used as a value here."

I am not sure what I have done wrong...?

import code:
``import AccountManager from "react-native-account-manager";``

usage:
``await AccountManager.addAccountExplicitly(
                        "AccountName",
                        email,
                        password
                    );``

It is in the usage code that VS Code is having an issue.

I am using React-Native ^0.61.5

Thanks in advance for the help.

**Comment by MarcoScabbiolo** [comment]
Hi @marcodafonseca , we have a fix pending of release for the typings.
@nicosefer can we release master?

**Comment by MarcoScabbiolo** [comment]
Solved in `1.0.9` release

**Comment by marcodafonseca** [comment]
Thanks for the fix, guys. It's working on my side now :)
